/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.numaproj.numaflow.ApiClient;
/**
 * GetJetStreamServiceSpecReq
 */
@JsonPropertyOrder({
  GetJetStreamServiceSpecReq.JSON_PROPERTY_CLIENT_PORT,
  GetJetStreamServiceSpecReq.JSON_PROPERTY_CLUSTER_PORT,
  GetJetStreamServiceSpecReq.JSON_PROPERTY_LABELS,
  GetJetStreamServiceSpecReq.JSON_PROPERTY_METRICS_PORT,
  GetJetStreamServiceSpecReq.JSON_PROPERTY_MONITOR_PORT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class GetJetStreamServiceSpecReq {
  public static final String JSON_PROPERTY_CLIENT_PORT = "ClientPort";
  private Integer clientPort;

  public static final String JSON_PROPERTY_CLUSTER_PORT = "ClusterPort";
  private Integer clusterPort;

  public static final String JSON_PROPERTY_LABELS = "Labels";
  private Map<String, String> labels = new HashMap<>();

  public static final String JSON_PROPERTY_METRICS_PORT = "MetricsPort";
  private Integer metricsPort;

  public static final String JSON_PROPERTY_MONITOR_PORT = "MonitorPort";
  private Integer monitorPort;

  public GetJetStreamServiceSpecReq() { 
  }

  public GetJetStreamServiceSpecReq clientPort(Integer clientPort) {
    this.clientPort = clientPort;
    return this;
  }

  /**
   * Get clientPort
   * @return clientPort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getClientPort() {
    return clientPort;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientPort(Integer clientPort) {
    this.clientPort = clientPort;
  }


  public GetJetStreamServiceSpecReq clusterPort(Integer clusterPort) {
    this.clusterPort = clusterPort;
    return this;
  }

  /**
   * Get clusterPort
   * @return clusterPort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLUSTER_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getClusterPort() {
    return clusterPort;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClusterPort(Integer clusterPort) {
    this.clusterPort = clusterPort;
  }


  public GetJetStreamServiceSpecReq labels(Map<String, String> labels) {
    this.labels = labels;
    return this;
  }

  public GetJetStreamServiceSpecReq putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public GetJetStreamServiceSpecReq metricsPort(Integer metricsPort) {
    this.metricsPort = metricsPort;
    return this;
  }

  /**
   * Get metricsPort
   * @return metricsPort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METRICS_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMetricsPort() {
    return metricsPort;
  }


  @JsonProperty(JSON_PROPERTY_METRICS_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetricsPort(Integer metricsPort) {
    this.metricsPort = metricsPort;
  }


  public GetJetStreamServiceSpecReq monitorPort(Integer monitorPort) {
    this.monitorPort = monitorPort;
    return this;
  }

  /**
   * Get monitorPort
   * @return monitorPort
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MONITOR_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMonitorPort() {
    return monitorPort;
  }


  @JsonProperty(JSON_PROPERTY_MONITOR_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMonitorPort(Integer monitorPort) {
    this.monitorPort = monitorPort;
  }


  /**
   * Return true if this GetJetStreamServiceSpecReq object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetJetStreamServiceSpecReq getJetStreamServiceSpecReq = (GetJetStreamServiceSpecReq) o;
    return Objects.equals(this.clientPort, getJetStreamServiceSpecReq.clientPort) &&
        Objects.equals(this.clusterPort, getJetStreamServiceSpecReq.clusterPort) &&
        Objects.equals(this.labels, getJetStreamServiceSpecReq.labels) &&
        Objects.equals(this.metricsPort, getJetStreamServiceSpecReq.metricsPort) &&
        Objects.equals(this.monitorPort, getJetStreamServiceSpecReq.monitorPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientPort, clusterPort, labels, metricsPort, monitorPort);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetJetStreamServiceSpecReq {\n");
    sb.append("    clientPort: ").append(toIndentedString(clientPort)).append("\n");
    sb.append("    clusterPort: ").append(toIndentedString(clusterPort)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    metricsPort: ").append(toIndentedString(metricsPort)).append("\n");
    sb.append("    monitorPort: ").append(toIndentedString(monitorPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ClientPort` to the URL query string
    if (getClientPort() != null) {
      joiner.add(String.format("%sClientPort%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClientPort()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ClusterPort` to the URL query string
    if (getClusterPort() != null) {
      joiner.add(String.format("%sClusterPort%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClusterPort()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `Labels` to the URL query string
    if (getLabels() != null) {
      for (String _key : getLabels().keySet()) {
        joiner.add(String.format("%sLabels%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getLabels().get(_key), URLEncoder.encode(ApiClient.valueToString(getLabels().get(_key)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `MetricsPort` to the URL query string
    if (getMetricsPort() != null) {
      joiner.add(String.format("%sMetricsPort%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMetricsPort()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `MonitorPort` to the URL query string
    if (getMonitorPort() != null) {
      joiner.add(String.format("%sMonitorPort%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMonitorPort()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

