/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.JetStreamBufferService;
import io.numaproj.numaflow.models.RedisBufferService;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.numaproj.numaflow.ApiClient;
/**
 * InterStepBufferServiceSpec
 */
@JsonPropertyOrder({
  InterStepBufferServiceSpec.JSON_PROPERTY_JETSTREAM,
  InterStepBufferServiceSpec.JSON_PROPERTY_REDIS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class InterStepBufferServiceSpec {
  public static final String JSON_PROPERTY_JETSTREAM = "jetstream";
  private JetStreamBufferService jetstream;

  public static final String JSON_PROPERTY_REDIS = "redis";
  private RedisBufferService redis;

  public InterStepBufferServiceSpec() { 
  }

  public InterStepBufferServiceSpec jetstream(JetStreamBufferService jetstream) {
    this.jetstream = jetstream;
    return this;
  }

  /**
   * Get jetstream
   * @return jetstream
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JETSTREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JetStreamBufferService getJetstream() {
    return jetstream;
  }


  @JsonProperty(JSON_PROPERTY_JETSTREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJetstream(JetStreamBufferService jetstream) {
    this.jetstream = jetstream;
  }


  public InterStepBufferServiceSpec redis(RedisBufferService redis) {
    this.redis = redis;
    return this;
  }

  /**
   * Get redis
   * @return redis
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RedisBufferService getRedis() {
    return redis;
  }


  @JsonProperty(JSON_PROPERTY_REDIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedis(RedisBufferService redis) {
    this.redis = redis;
  }


  /**
   * Return true if this InterStepBufferServiceSpec object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterStepBufferServiceSpec interStepBufferServiceSpec = (InterStepBufferServiceSpec) o;
    return Objects.equals(this.jetstream, interStepBufferServiceSpec.jetstream) &&
        Objects.equals(this.redis, interStepBufferServiceSpec.redis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jetstream, redis);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterStepBufferServiceSpec {\n");
    sb.append("    jetstream: ").append(toIndentedString(jetstream)).append("\n");
    sb.append("    redis: ").append(toIndentedString(redis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `jetstream` to the URL query string
    if (getJetstream() != null) {
      joiner.add(getJetstream().toUrlQueryString(prefix + "jetstream" + suffix));
    }

    // add `redis` to the URL query string
    if (getRedis() != null) {
      joiner.add(getRedis().toUrlQueryString(prefix + "redis" + suffix));
    }

    return joiner.toString();
  }
}

