/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.KafkaSink;
import io.numaproj.numaflow.models.UDSink;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AbstractSink
 */
class AbstractSinkTest {
    private final AbstractSink model = new AbstractSink();

    /**
     * Model tests for AbstractSink
     */
    @Test
    void testAbstractSink() {
        // TODO: test AbstractSink
    }

    /**
     * Test the property 'blackhole'
     */
    @Test
    void blackholeTest() {
        // TODO: test blackhole
    }

    /**
     * Test the property 'kafka'
     */
    @Test
    void kafkaTest() {
        // TODO: test kafka
    }

    /**
     * Test the property 'log'
     */
    @Test
    void logTest() {
        // TODO: test log
    }

    /**
     * Test the property 'udsink'
     */
    @Test
    void udsinkTest() {
        // TODO: test udsink
    }

}
