/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.JetStreamConfig;
import io.numaproj.numaflow.models.RedisConfig;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BufferServiceConfig
 */
class BufferServiceConfigTest {
    private final BufferServiceConfig model = new BufferServiceConfig();

    /**
     * Model tests for BufferServiceConfig
     */
    @Test
    void testBufferServiceConfig() {
        // TODO: test BufferServiceConfig
    }

    /**
     * Test the property 'jetstream'
     */
    @Test
    void jetstreamTest() {
        // TODO: test jetstream
    }

    /**
     * Test the property 'redis'
     */
    @Test
    void redisTest() {
        // TODO: test redis
    }

}
