/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1EnvFromSource;
import io.kubernetes.client.openapi.models.V1EnvVar;
import io.kubernetes.client.openapi.models.V1ResourceRequirements;
import io.kubernetes.client.openapi.models.V1SecurityContext;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContainerTemplate
 */
class ContainerTemplateTest {
    private final ContainerTemplate model = new ContainerTemplate();

    /**
     * Model tests for ContainerTemplate
     */
    @Test
    void testContainerTemplate() {
        // TODO: test ContainerTemplate
    }

    /**
     * Test the property 'env'
     */
    @Test
    void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'envFrom'
     */
    @Test
    void envFromTest() {
        // TODO: test envFrom
    }

    /**
     * Test the property 'imagePullPolicy'
     */
    @Test
    void imagePullPolicyTest() {
        // TODO: test imagePullPolicy
    }

    /**
     * Test the property 'resources'
     */
    @Test
    void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    void securityContextTest() {
        // TODO: test securityContext
    }

}
