/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EdgeLimits
 */
public class EdgeLimitsTest {
    private final EdgeLimits model = new EdgeLimits();

    /**
     * Model tests for EdgeLimits
     */
    @Test
    public void testEdgeLimits() {
        // TODO: test EdgeLimits
    }

    /**
     * Test the property 'bufferMaxLength'
     */
    @Test
    public void bufferMaxLengthTest() {
        // TODO: test bufferMaxLength
    }

    /**
     * Test the property 'bufferUsageLimit'
     */
    @Test
    public void bufferUsageLimitTest() {
        // TODO: test bufferUsageLimit
    }

}
