/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FixedWindow
 */
class FixedWindowTest {
    private final FixedWindow model = new FixedWindow();

    /**
     * Model tests for FixedWindow
     */
    @Test
    void testFixedWindow() {
        // TODO: test FixedWindow
    }

    /**
     * Test the property 'length'
     */
    @Test
    void lengthTest() {
        // TODO: test length
    }

    /**
     * Test the property 'streaming'
     */
    @Test
    void streamingTest() {
        // TODO: test streaming
    }

}
