/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GeneratorSource
 */
public class GeneratorSourceTest {
    private final GeneratorSource model = new GeneratorSource();

    /**
     * Model tests for GeneratorSource
     */
    @Test
    public void testGeneratorSource() {
        // TODO: test GeneratorSource
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'msgSize'
     */
    @Test
    public void msgSizeTest() {
        // TODO: test msgSize
    }

    /**
     * Test the property 'rpu'
     */
    @Test
    public void rpuTest() {
        // TODO: test rpu
    }

}
