/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GeneratorSource
 */
class GeneratorSourceTest {
    private final GeneratorSource model = new GeneratorSource();

    /**
     * Model tests for GeneratorSource
     */
    @Test
    void testGeneratorSource() {
        // TODO: test GeneratorSource
    }

    /**
     * Test the property 'duration'
     */
    @Test
    void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'jitter'
     */
    @Test
    void jitterTest() {
        // TODO: test jitter
    }

    /**
     * Test the property 'keyCount'
     */
    @Test
    void keyCountTest() {
        // TODO: test keyCount
    }

    /**
     * Test the property 'msgSize'
     */
    @Test
    void msgSizeTest() {
        // TODO: test msgSize
    }

    /**
     * Test the property 'rpu'
     */
    @Test
    void rpuTest() {
        // TODO: test rpu
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

}
