/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.6.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetJetStreamStatefulSetSpecReq
 */
public class GetJetStreamStatefulSetSpecReqTest {
    private final GetJetStreamStatefulSetSpecReq model = new GetJetStreamStatefulSetSpecReq();

    /**
     * Model tests for GetJetStreamStatefulSetSpecReq
     */
    @Test
    public void testGetJetStreamStatefulSetSpecReq() {
        // TODO: test GetJetStreamStatefulSetSpecReq
    }

    /**
     * Test the property 'clientPort'
     */
    @Test
    public void clientPortTest() {
        // TODO: test clientPort
    }

    /**
     * Test the property 'clusterPort'
     */
    @Test
    public void clusterPortTest() {
        // TODO: test clusterPort
    }

    /**
     * Test the property 'configMapName'
     */
    @Test
    public void configMapNameTest() {
        // TODO: test configMapName
    }

    /**
     * Test the property 'configReloaderImage'
     */
    @Test
    public void configReloaderImageTest() {
        // TODO: test configReloaderImage
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'metricsExporterImage'
     */
    @Test
    public void metricsExporterImageTest() {
        // TODO: test metricsExporterImage
    }

    /**
     * Test the property 'metricsPort'
     */
    @Test
    public void metricsPortTest() {
        // TODO: test metricsPort
    }

    /**
     * Test the property 'monitorPort'
     */
    @Test
    public void monitorPortTest() {
        // TODO: test monitorPort
    }

    /**
     * Test the property 'natsImage'
     */
    @Test
    public void natsImageTest() {
        // TODO: test natsImage
    }

    /**
     * Test the property 'pvcNameIfNeeded'
     */
    @Test
    public void pvcNameIfNeededTest() {
        // TODO: test pvcNameIfNeeded
    }

    /**
     * Test the property 'serverAuthSecretName'
     */
    @Test
    public void serverAuthSecretNameTest() {
        // TODO: test serverAuthSecretName
    }

    /**
     * Test the property 'serverEncryptionSecretName'
     */
    @Test
    public void serverEncryptionSecretNameTest() {
        // TODO: test serverEncryptionSecretName
    }

    /**
     * Test the property 'serviceName'
     */
    @Test
    public void serviceNameTest() {
        // TODO: test serviceName
    }

    /**
     * Test the property 'startCommand'
     */
    @Test
    public void startCommandTest() {
        // TODO: test startCommand
    }

}
