/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.PBQStorage;
import io.numaproj.numaflow.models.Window;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GroupBy
 */
class GroupByTest {
    private final GroupBy model = new GroupBy();

    /**
     * Model tests for GroupBy
     */
    @Test
    void testGroupBy() {
        // TODO: test GroupBy
    }

    /**
     * Test the property 'allowedLateness'
     */
    @Test
    void allowedLatenessTest() {
        // TODO: test allowedLateness
    }

    /**
     * Test the property 'keyed'
     */
    @Test
    void keyedTest() {
        // TODO: test keyed
    }

    /**
     * Test the property 'storage'
     */
    @Test
    void storageTest() {
        // TODO: test storage
    }

    /**
     * Test the property 'window'
     */
    @Test
    void windowTest() {
        // TODO: test window
    }

}
