/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GSSAPI
 */
class GSSAPITest {
    private final GSSAPI model = new GSSAPI();

    /**
     * Model tests for GSSAPI
     */
    @Test
    void testGSSAPI() {
        // TODO: test GSSAPI
    }

    /**
     * Test the property 'authType'
     */
    @Test
    void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'kerberosConfigSecret'
     */
    @Test
    void kerberosConfigSecretTest() {
        // TODO: test kerberosConfigSecret
    }

    /**
     * Test the property 'keytabSecret'
     */
    @Test
    void keytabSecretTest() {
        // TODO: test keytabSecret
    }

    /**
     * Test the property 'passwordSecret'
     */
    @Test
    void passwordSecretTest() {
        // TODO: test passwordSecret
    }

    /**
     * Test the property 'realm'
     */
    @Test
    void realmTest() {
        // TODO: test realm
    }

    /**
     * Test the property 'serviceName'
     */
    @Test
    void serviceNameTest() {
        // TODO: test serviceName
    }

    /**
     * Test the property 'usernameSecret'
     */
    @Test
    void usernameSecretTest() {
        // TODO: test usernameSecret
    }

}
