/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1Affinity;
import io.kubernetes.client.openapi.models.V1LocalObjectReference;
import io.kubernetes.client.openapi.models.V1PodDNSConfig;
import io.kubernetes.client.openapi.models.V1PodSecurityContext;
import io.kubernetes.client.openapi.models.V1Toleration;
import io.numaproj.numaflow.models.ContainerTemplate;
import io.numaproj.numaflow.models.Metadata;
import io.numaproj.numaflow.models.PersistenceStrategy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JetStreamBufferService
 */
class JetStreamBufferServiceTest {
    private final JetStreamBufferService model = new JetStreamBufferService();

    /**
     * Model tests for JetStreamBufferService
     */
    @Test
    void testJetStreamBufferService() {
        // TODO: test JetStreamBufferService
    }

    /**
     * Test the property 'affinity'
     */
    @Test
    void affinityTest() {
        // TODO: test affinity
    }

    /**
     * Test the property 'automountServiceAccountToken'
     */
    @Test
    void automountServiceAccountTokenTest() {
        // TODO: test automountServiceAccountToken
    }

    /**
     * Test the property 'bufferConfig'
     */
    @Test
    void bufferConfigTest() {
        // TODO: test bufferConfig
    }

    /**
     * Test the property 'containerTemplate'
     */
    @Test
    void containerTemplateTest() {
        // TODO: test containerTemplate
    }

    /**
     * Test the property 'dnsConfig'
     */
    @Test
    void dnsConfigTest() {
        // TODO: test dnsConfig
    }

    /**
     * Test the property 'dnsPolicy'
     */
    @Test
    void dnsPolicyTest() {
        // TODO: test dnsPolicy
    }

    /**
     * Test the property 'encryption'
     */
    @Test
    void encryptionTest() {
        // TODO: test encryption
    }

    /**
     * Test the property 'imagePullSecrets'
     */
    @Test
    void imagePullSecretsTest() {
        // TODO: test imagePullSecrets
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'metricsContainerTemplate'
     */
    @Test
    void metricsContainerTemplateTest() {
        // TODO: test metricsContainerTemplate
    }

    /**
     * Test the property 'nodeSelector'
     */
    @Test
    void nodeSelectorTest() {
        // TODO: test nodeSelector
    }

    /**
     * Test the property 'persistence'
     */
    @Test
    void persistenceTest() {
        // TODO: test persistence
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'priorityClassName'
     */
    @Test
    void priorityClassNameTest() {
        // TODO: test priorityClassName
    }

    /**
     * Test the property 'reloaderContainerTemplate'
     */
    @Test
    void reloaderContainerTemplateTest() {
        // TODO: test reloaderContainerTemplate
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'runtimeClassName'
     */
    @Test
    void runtimeClassNameTest() {
        // TODO: test runtimeClassName
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    void securityContextTest() {
        // TODO: test securityContext
    }

    /**
     * Test the property 'serviceAccountName'
     */
    @Test
    void serviceAccountNameTest() {
        // TODO: test serviceAccountName
    }

    /**
     * Test the property 'settings'
     */
    @Test
    void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'startArgs'
     */
    @Test
    void startArgsTest() {
        // TODO: test startArgs
    }

    /**
     * Test the property 'tls'
     */
    @Test
    void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'tolerations'
     */
    @Test
    void tolerationsTest() {
        // TODO: test tolerations
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

}
