/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1Affinity;
import io.kubernetes.client.openapi.models.V1LocalObjectReference;
import io.kubernetes.client.openapi.models.V1PodDNSConfig;
import io.kubernetes.client.openapi.models.V1PodSecurityContext;
import io.kubernetes.client.openapi.models.V1Toleration;
import io.numaproj.numaflow.models.ContainerTemplate;
import io.numaproj.numaflow.models.Metadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobTemplate
 */
class JobTemplateTest {
    private final JobTemplate model = new JobTemplate();

    /**
     * Model tests for JobTemplate
     */
    @Test
    void testJobTemplate() {
        // TODO: test JobTemplate
    }

    /**
     * Test the property 'affinity'
     */
    @Test
    void affinityTest() {
        // TODO: test affinity
    }

    /**
     * Test the property 'automountServiceAccountToken'
     */
    @Test
    void automountServiceAccountTokenTest() {
        // TODO: test automountServiceAccountToken
    }

    /**
     * Test the property 'backoffLimit'
     */
    @Test
    void backoffLimitTest() {
        // TODO: test backoffLimit
    }

    /**
     * Test the property 'containerTemplate'
     */
    @Test
    void containerTemplateTest() {
        // TODO: test containerTemplate
    }

    /**
     * Test the property 'dnsConfig'
     */
    @Test
    void dnsConfigTest() {
        // TODO: test dnsConfig
    }

    /**
     * Test the property 'dnsPolicy'
     */
    @Test
    void dnsPolicyTest() {
        // TODO: test dnsPolicy
    }

    /**
     * Test the property 'imagePullSecrets'
     */
    @Test
    void imagePullSecretsTest() {
        // TODO: test imagePullSecrets
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'nodeSelector'
     */
    @Test
    void nodeSelectorTest() {
        // TODO: test nodeSelector
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'priorityClassName'
     */
    @Test
    void priorityClassNameTest() {
        // TODO: test priorityClassName
    }

    /**
     * Test the property 'runtimeClassName'
     */
    @Test
    void runtimeClassNameTest() {
        // TODO: test runtimeClassName
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    void securityContextTest() {
        // TODO: test securityContext
    }

    /**
     * Test the property 'serviceAccountName'
     */
    @Test
    void serviceAccountNameTest() {
        // TODO: test serviceAccountName
    }

    /**
     * Test the property 'tolerations'
     */
    @Test
    void tolerationsTest() {
        // TODO: test tolerations
    }

    /**
     * Test the property 'ttlSecondsAfterFinished'
     */
    @Test
    void ttlSecondsAfterFinishedTest() {
        // TODO: test ttlSecondsAfterFinished
    }

}
