/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1EmptyDirVolumeSource;
import io.numaproj.numaflow.models.PersistenceStrategy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PBQStorage
 */
public class PBQStorageTest {
    private final PBQStorage model = new PBQStorage();

    /**
     * Model tests for PBQStorage
     */
    @Test
    public void testPBQStorage() {
        // TODO: test PBQStorage
    }

    /**
     * Test the property 'emptyDir'
     */
    @Test
    public void emptyDirTest() {
        // TODO: test emptyDir
    }

    /**
     * Test the property 'persistentVolumeClaim'
     */
    @Test
    public void persistentVolumeClaimTest() {
        // TODO: test persistentVolumeClaim
    }

}
