/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RedisSettings
 */
public class RedisSettingsTest {
    private final RedisSettings model = new RedisSettings();

    /**
     * Model tests for RedisSettings
     */
    @Test
    public void testRedisSettings() {
        // TODO: test RedisSettings
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'redis'
     */
    @Test
    public void redisTest() {
        // TODO: test redis
    }

    /**
     * Test the property 'replica'
     */
    @Test
    public void replicaTest() {
        // TODO: test replica
    }

    /**
     * Test the property 'sentinel'
     */
    @Test
    public void sentinelTest() {
        // TODO: test sentinel
    }

}
