/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SASLPlain
 */
public class SASLPlainTest {
    private final SASLPlain model = new SASLPlain();

    /**
     * Model tests for SASLPlain
     */
    @Test
    public void testSASLPlain() {
        // TODO: test SASLPlain
    }

    /**
     * Test the property 'handshake'
     */
    @Test
    public void handshakeTest() {
        // TODO: test handshake
    }

    /**
     * Test the property 'passwordSecret'
     */
    @Test
    public void passwordSecretTest() {
        // TODO: test passwordSecret
    }

    /**
     * Test the property 'userSecret'
     */
    @Test
    public void userSecretTest() {
        // TODO: test userSecret
    }

}
