/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1Volume;
import io.numaproj.numaflow.models.Container;
import io.numaproj.numaflow.models.SideInputTrigger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SideInput
 */
class SideInputTest {
    private final SideInput model = new SideInput();

    /**
     * Model tests for SideInput
     */
    @Test
    void testSideInput() {
        // TODO: test SideInput
    }

    /**
     * Test the property 'container'
     */
    @Test
    void containerTest() {
        // TODO: test container
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'trigger'
     */
    @Test
    void triggerTest() {
        // TODO: test trigger
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    void volumesTest() {
        // TODO: test volumes
    }

}
