/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.GeneratorSource;
import io.numaproj.numaflow.models.HTTPSource;
import io.numaproj.numaflow.models.KafkaSource;
import io.numaproj.numaflow.models.NatsSource;
import io.numaproj.numaflow.models.UDSource;
import io.numaproj.numaflow.models.UDTransformer;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Source
 */
class SourceTest {
    private final Source model = new Source();

    /**
     * Model tests for Source
     */
    @Test
    void testSource() {
        // TODO: test Source
    }

    /**
     * Test the property 'generator'
     */
    @Test
    void generatorTest() {
        // TODO: test generator
    }

    /**
     * Test the property 'http'
     */
    @Test
    void httpTest() {
        // TODO: test http
    }

    /**
     * Test the property 'kafka'
     */
    @Test
    void kafkaTest() {
        // TODO: test kafka
    }

    /**
     * Test the property 'nats'
     */
    @Test
    void natsTest() {
        // TODO: test nats
    }

    /**
     * Test the property 'transformer'
     */
    @Test
    void transformerTest() {
        // TODO: test transformer
    }

    /**
     * Test the property 'udsource'
     */
    @Test
    void udsourceTest() {
        // TODO: test udsource
    }

}
