/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TLS
 */
public class TLSTest {
    private final TLS model = new TLS();

    /**
     * Model tests for TLS
     */
    @Test
    public void testTLS() {
        // TODO: test TLS
    }

    /**
     * Test the property 'caCertSecret'
     */
    @Test
    public void caCertSecretTest() {
        // TODO: test caCertSecret
    }

    /**
     * Test the property 'clientCertSecret'
     */
    @Test
    public void clientCertSecretTest() {
        // TODO: test clientCertSecret
    }

    /**
     * Test the property 'clientKeySecret'
     */
    @Test
    public void clientKeySecretTest() {
        // TODO: test clientKeySecret
    }

    /**
     * Test the property 'insecureSkipVerify'
     */
    @Test
    public void insecureSkipVerifyTest() {
        // TODO: test insecureSkipVerify
    }

}
