/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TLS
 */
class TLSTest {
    private final TLS model = new TLS();

    /**
     * Model tests for TLS
     */
    @Test
    void testTLS() {
        // TODO: test TLS
    }

    /**
     * Test the property 'caCertSecret'
     */
    @Test
    void caCertSecretTest() {
        // TODO: test caCertSecret
    }

    /**
     * Test the property 'certSecret'
     */
    @Test
    void certSecretTest() {
        // TODO: test certSecret
    }

    /**
     * Test the property 'insecureSkipVerify'
     */
    @Test
    void insecureSkipVerifyTest() {
        // TODO: test insecureSkipVerify
    }

    /**
     * Test the property 'keySecret'
     */
    @Test
    void keySecretTest() {
        // TODO: test keySecret
    }

}
