/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.numaproj.numaflow.models.FixedWindow;
import io.numaproj.numaflow.models.SessionWindow;
import io.numaproj.numaflow.models.SlidingWindow;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Window
 */
class WindowTest {
    private final Window model = new Window();

    /**
     * Model tests for Window
     */
    @Test
    void testWindow() {
        // TODO: test Window
    }

    /**
     * Test the property 'fixed'
     */
    @Test
    void fixedTest() {
        // TODO: test fixed
    }

    /**
     * Test the property 'session'
     */
    @Test
    void sessionTest() {
        // TODO: test session
    }

    /**
     * Test the property 'sliding'
     */
    @Test
    void slidingTest() {
        // TODO: test sliding
    }

}
